#!/usr/bin/env php
<?php

// Include the autoloader
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} elseif (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/src/bootstrap.php';
}

// Bootstrap the console application
new \StatonLab\TripalTestSuite\Console\TripalTest();
